name: Deploy for preview

on: push

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          description: 'Preview my app'
          environment: preview

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: aws s3 sync ./web s3://demo.wissver.com

      - name: Update Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E39S93Y0SWLO38 --paths "/*"